#if os(iOS) || os(watchOS) || os(tvOS)
    import Foundation
    import MobileCoreServices
#elseif os(OSX)
    import Foundation
    import CoreServices
#endif

extension UniformTypeIdentifier {
    public static let item = UniformTypeIdentifier(rawValue: kUTTypeItem as String)
    public static let content = UniformTypeIdentifier(rawValue: kUTTypeContent as String)
    public static let compositeContent = UniformTypeIdentifier(rawValue: kUTTypeCompositeContent as String)
    public static let message = UniformTypeIdentifier(rawValue: kUTTypeMessage as String)
    public static let contact = UniformTypeIdentifier(rawValue: kUTTypeContact as String)
    public static let archive = UniformTypeIdentifier(rawValue: kUTTypeArchive as String)
    public static let diskImage = UniformTypeIdentifier(rawValue: kUTTypeDiskImage as String)
    public static let data = UniformTypeIdentifier(rawValue: kUTTypeData as String)
    public static let directory = UniformTypeIdentifier(rawValue: kUTTypeDirectory as String)
    public static let resolvable = UniformTypeIdentifier(rawValue: kUTTypeResolvable as String)
    public static let symLink = UniformTypeIdentifier(rawValue: kUTTypeSymLink as String)
    public static let executable = UniformTypeIdentifier(rawValue: kUTTypeExecutable as String)
    public static let mountPoint = UniformTypeIdentifier(rawValue: kUTTypeMountPoint as String)
    public static let aliasFile = UniformTypeIdentifier(rawValue: kUTTypeAliasFile as String)
    public static let aliasRecord = UniformTypeIdentifier(rawValue: kUTTypeAliasRecord as String)
    public static let urlBookmarkData = UniformTypeIdentifier(rawValue: kUTTypeURLBookmarkData as String)
    public static let url = UniformTypeIdentifier(rawValue: kUTTypeURL as String)
    public static let fileURL = UniformTypeIdentifier(rawValue: kUTTypeFileURL as String)
    public static let text = UniformTypeIdentifier(rawValue: kUTTypeText as String)
    public static let plainText = UniformTypeIdentifier(rawValue: kUTTypePlainText as String)
    public static let utf8PlainText = UniformTypeIdentifier(rawValue: kUTTypeUTF8PlainText as String)
    public static let utf16ExternalPlainText = UniformTypeIdentifier(rawValue: kUTTypeUTF16ExternalPlainText as String)
    public static let utf16PlainText = UniformTypeIdentifier(rawValue: kUTTypeUTF16PlainText as String)
    public static let delimitedText = UniformTypeIdentifier(rawValue: kUTTypeDelimitedText as String)
    public static let commaSeparatedText = UniformTypeIdentifier(rawValue: kUTTypeCommaSeparatedText as String)
    public static let tabSeparatedText = UniformTypeIdentifier(rawValue: kUTTypeTabSeparatedText as String)
    public static let utf8TabSeparatedText = UniformTypeIdentifier(rawValue: kUTTypeUTF8TabSeparatedText as String)
    public static let rtf = UniformTypeIdentifier(rawValue: kUTTypeRTF as String)
    public static let html = UniformTypeIdentifier(rawValue: kUTTypeHTML as String)
    public static let xml = UniformTypeIdentifier(rawValue: kUTTypeXML as String)
    public static let sourceCode = UniformTypeIdentifier(rawValue: kUTTypeSourceCode as String)
    public static let assemblyLanguageSource = UniformTypeIdentifier(rawValue: kUTTypeAssemblyLanguageSource as String)
    public static let cSource = UniformTypeIdentifier(rawValue: kUTTypeCSource as String)
    public static let objectiveCSource = UniformTypeIdentifier(rawValue: kUTTypeObjectiveCSource as String)
    public static let swiftSource = UniformTypeIdentifier(rawValue: kUTTypeSwiftSource as String)
    public static let cPlusPlusSource = UniformTypeIdentifier(rawValue: kUTTypeCPlusPlusSource as String)
    public static let objectiveCPlusPlusSource = UniformTypeIdentifier(rawValue: kUTTypeObjectiveCPlusPlusSource as String)
    public static let cHeader = UniformTypeIdentifier(rawValue: kUTTypeCHeader as String)
    public static let cPlusPlusHeader = UniformTypeIdentifier(rawValue: kUTTypeCPlusPlusHeader as String)
    public static let javaSource = UniformTypeIdentifier(rawValue: kUTTypeJavaSource as String)
    public static let script = UniformTypeIdentifier(rawValue: kUTTypeScript as String)
    public static let appleScript = UniformTypeIdentifier(rawValue: kUTTypeAppleScript as String)
    public static let osaScript = UniformTypeIdentifier(rawValue: kUTTypeOSAScript as String)
    public static let osaScriptBundle = UniformTypeIdentifier(rawValue: kUTTypeOSAScriptBundle as String)
    public static let javaScript = UniformTypeIdentifier(rawValue: kUTTypeJavaScript as String)
    public static let shellScript = UniformTypeIdentifier(rawValue: kUTTypeShellScript as String)
    public static let perlScript = UniformTypeIdentifier(rawValue: kUTTypePerlScript as String)
    public static let pythonScript = UniformTypeIdentifier(rawValue: kUTTypePythonScript as String)
    public static let rubyScript = UniformTypeIdentifier(rawValue: kUTTypeRubyScript as String)
    public static let phpScript = UniformTypeIdentifier(rawValue: kUTTypePHPScript as String)
    public static let json = UniformTypeIdentifier(rawValue: kUTTypeJSON as String)
    public static let propertyList = UniformTypeIdentifier(rawValue: kUTTypePropertyList as String)
    public static let xmlPropertyList = UniformTypeIdentifier(rawValue: kUTTypeXMLPropertyList as String)
    public static let binaryPropertyList = UniformTypeIdentifier(rawValue: kUTTypeBinaryPropertyList as String)
    public static let pdf = UniformTypeIdentifier(rawValue: kUTTypePDF as String)
    public static let rtfd = UniformTypeIdentifier(rawValue: kUTTypeRTFD as String)
    public static let flatRTFD = UniformTypeIdentifier(rawValue: kUTTypeFlatRTFD as String)
    public static let txnTextAndMultimediaData = UniformTypeIdentifier(rawValue: kUTTypeTXNTextAndMultimediaData as String)
    public static let webArchive = UniformTypeIdentifier(rawValue: kUTTypeWebArchive as String)
    public static let image = UniformTypeIdentifier(rawValue: kUTTypeImage as String)
    public static let heifStandard = UniformTypeIdentifier(rawValue: "public.heif-standard")
    public static let heif = UniformTypeIdentifier(rawValue: "public.heif")
    public static let jpeg = UniformTypeIdentifier(rawValue: kUTTypeJPEG as String)
    public static let jpeg2000 = UniformTypeIdentifier(rawValue: kUTTypeJPEG2000 as String)
    public static let tiff = UniformTypeIdentifier(rawValue: kUTTypeTIFF as String)
    public static let pict = UniformTypeIdentifier(rawValue: kUTTypePICT as String)
    public static let gif = UniformTypeIdentifier(rawValue: kUTTypeGIF as String)
    public static let png = UniformTypeIdentifier(rawValue: kUTTypePNG as String)
    public static let quickTimeImage = UniformTypeIdentifier(rawValue: kUTTypeQuickTimeImage as String)
    public static let appleICNS = UniformTypeIdentifier(rawValue: kUTTypeAppleICNS as String)
    public static let bmp = UniformTypeIdentifier(rawValue: kUTTypeBMP as String)
    public static let ico = UniformTypeIdentifier(rawValue: kUTTypeICO as String)
    public static let rawImage = UniformTypeIdentifier(rawValue: kUTTypeRawImage as String)
    public static let scalableVectorGraphics = UniformTypeIdentifier(rawValue: kUTTypeScalableVectorGraphics as String)
    public static let heic = UniformTypeIdentifier(rawValue: "public.heic")
    public static let livePhoto = UniformTypeIdentifier(rawValue: kUTTypeLivePhoto as String)
    public static let audiovisualContent = UniformTypeIdentifier(rawValue: kUTTypeAudiovisualContent as String)
    public static let movie = UniformTypeIdentifier(rawValue: kUTTypeMovie as String)
    public static let video = UniformTypeIdentifier(rawValue: kUTTypeVideo as String)
    public static let audio = UniformTypeIdentifier(rawValue: kUTTypeAudio as String)
    public static let quickTimeMovie = UniformTypeIdentifier(rawValue: kUTTypeQuickTimeMovie as String)
    public static let mpeg = UniformTypeIdentifier(rawValue: kUTTypeMPEG as String)
    public static let mpeg2Video = UniformTypeIdentifier(rawValue: kUTTypeMPEG2Video as String)
    public static let mpeg2TransportStream = UniformTypeIdentifier(rawValue: kUTTypeMPEG2TransportStream as String)
    public static let mp3 = UniformTypeIdentifier(rawValue: kUTTypeMP3 as String)
    public static let mpeg4 = UniformTypeIdentifier(rawValue: kUTTypeMPEG4 as String)
    public static let mpeg4Audio = UniformTypeIdentifier(rawValue: kUTTypeMPEG4Audio as String)
    public static let appleProtectedMPEG4Audio = UniformTypeIdentifier(rawValue: kUTTypeAppleProtectedMPEG4Audio as String)
    public static let appleProtectedMPEG4Video = UniformTypeIdentifier(rawValue: kUTTypeAppleProtectedMPEG4Video as String)
    public static let aviMovie = UniformTypeIdentifier(rawValue: kUTTypeAVIMovie as String)
    public static let audioInterchangeFileFormat = UniformTypeIdentifier(rawValue: kUTTypeAudioInterchangeFileFormat as String)
    public static let waveformAudio = UniformTypeIdentifier(rawValue: kUTTypeWaveformAudio as String)
    public static let midiAudio = UniformTypeIdentifier(rawValue: kUTTypeMIDIAudio as String)
    public static let playlist = UniformTypeIdentifier(rawValue: kUTTypePlaylist as String)
    public static let m3uPlaylist = UniformTypeIdentifier(rawValue: kUTTypeM3UPlaylist as String)
    public static let folder = UniformTypeIdentifier(rawValue: kUTTypeFolder as String)
    public static let volume = UniformTypeIdentifier(rawValue: kUTTypeVolume as String)
    public static let package = UniformTypeIdentifier(rawValue: kUTTypePackage as String)
    public static let bundle = UniformTypeIdentifier(rawValue: kUTTypeBundle as String)
    public static let pluginBundle = UniformTypeIdentifier(rawValue: kUTTypePluginBundle as String)
    public static let spotlightImporter = UniformTypeIdentifier(rawValue: kUTTypeSpotlightImporter as String)
    public static let quickLookGenerator = UniformTypeIdentifier(rawValue: kUTTypeQuickLookGenerator as String)
    public static let xpcService = UniformTypeIdentifier(rawValue: kUTTypeXPCService as String)
    public static let framework = UniformTypeIdentifier(rawValue: kUTTypeFramework as String)
    public static let application = UniformTypeIdentifier(rawValue: kUTTypeApplication as String)
    public static let applicationBundle = UniformTypeIdentifier(rawValue: kUTTypeApplicationBundle as String)
    public static let applicationFile = UniformTypeIdentifier(rawValue: kUTTypeApplicationFile as String)
    public static let unixExecutable = UniformTypeIdentifier(rawValue: kUTTypeUnixExecutable as String)
    public static let windowsExecutable = UniformTypeIdentifier(rawValue: kUTTypeWindowsExecutable as String)
    public static let javaClass = UniformTypeIdentifier(rawValue: kUTTypeJavaClass as String)
    public static let javaArchive = UniformTypeIdentifier(rawValue: kUTTypeJavaArchive as String)
    public static let systemPreferencesPane = UniformTypeIdentifier(rawValue: kUTTypeSystemPreferencesPane as String)
    public static let gnuZipArchive = UniformTypeIdentifier(rawValue: kUTTypeGNUZipArchive as String)
    public static let bzip2Archive = UniformTypeIdentifier(rawValue: kUTTypeBzip2Archive as String)
    public static let zipArchive = UniformTypeIdentifier(rawValue: kUTTypeZipArchive as String)
    public static let spreadsheet = UniformTypeIdentifier(rawValue: kUTTypeSpreadsheet as String)
    public static let presentation = UniformTypeIdentifier(rawValue: kUTTypePresentation as String)
    public static let database = UniformTypeIdentifier(rawValue: kUTTypeDatabase as String)
    public static let vCard = UniformTypeIdentifier(rawValue: kUTTypeVCard as String)
    public static let toDoItem = UniformTypeIdentifier(rawValue: kUTTypeToDoItem as String)
    public static let calendarEvent = UniformTypeIdentifier(rawValue: kUTTypeCalendarEvent as String)
    public static let emailMessage = UniformTypeIdentifier(rawValue: kUTTypeEmailMessage as String)
    public static let internetLocation = UniformTypeIdentifier(rawValue: kUTTypeInternetLocation as String)
    public static let inkText = UniformTypeIdentifier(rawValue: kUTTypeInkText as String)
    public static let font = UniformTypeIdentifier(rawValue: kUTTypeFont as String)
    public static let bookmark = UniformTypeIdentifier(rawValue: kUTTypeBookmark as String)
    public static let _3dContent = UniformTypeIdentifier(rawValue: kUTType3DContent as String)
    public static let pkcs12 = UniformTypeIdentifier(rawValue: kUTTypePKCS12 as String)
    public static let x509Certificate = UniformTypeIdentifier(rawValue: kUTTypeX509Certificate as String)
    public static let electronicPublication = UniformTypeIdentifier(rawValue: kUTTypeElectronicPublication as String)
    public static let log = UniformTypeIdentifier(rawValue: kUTTypeLog as String)
}

// https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html
extension UniformTypeIdentifier {
    public static let postscript = UniformTypeIdentifier(rawValue: "com.adobe.postscript")
    public static let encapsulatedPostscript = UniformTypeIdentifier(rawValue: "com.adobe.encapsulated-postscript")
    public static let photoshopImage = UniformTypeIdentifier(rawValue: "com.adobe.photoshop-image")
    public static let aiImage = UniformTypeIdentifier(rawValue: "com.adobe.illustrator.ai-image")
    public static let wordDocument = UniformTypeIdentifier(rawValue: "com.microsoft.word.doc")
    public static let excelSpreadsheet = UniformTypeIdentifier(rawValue: "com.microsoft.excel.xls")
    public static let powerpointPresentation = UniformTypeIdentifier(rawValue: "com.microsoft.powerpoint.ppt")
    public static let advancedSystems = UniformTypeIdentifier(rawValue: "com.microsoft.advanced-systems-format")
    public static let windowsMediaWM = UniformTypeIdentifier(rawValue: "com.microsoft.windows-media-wm")
    public static let windowsMediaWMV = UniformTypeIdentifier(rawValue: "com.microsoft.windows-media-wmv")
    public static let windowsMediaWMP = UniformTypeIdentifier(rawValue: "com.microsoft.windows-media-wmp")
    public static let windowsMediaWMA = UniformTypeIdentifier(rawValue: "com.microsoft.windows-media-wma")
    public static let advancedStreamRedirector = UniformTypeIdentifier(rawValue: "com.microsoft.advanced-stream-redirector")
    public static let windowsMediaWMX = UniformTypeIdentifier(rawValue: "com.microsoft.windows-media-wmx")
    public static let windowsMediaWVX = UniformTypeIdentifier(rawValue: "com.microsoft.windows-media-wvx")
    public static let windowsMediaWAX = UniformTypeIdentifier(rawValue: "com.microsoft.windows-media-wax")
    public static let keynotePresentation = UniformTypeIdentifier(rawValue: "com.apple.keynote.key")
    public static let keynoteTheme = UniformTypeIdentifier(rawValue: "com.apple.keynote.kth")
    public static let tgaImage = UniformTypeIdentifier(rawValue: "com.truevision.tga-image")
    public static let sgiImage = UniformTypeIdentifier(rawValue: "com.sgi.sgi-image")
    public static let openEXRImage = UniformTypeIdentifier(rawValue: "com.ilm.openexr-image")
    public static let flashPixImage = UniformTypeIdentifier(rawValue: "com.kodak.flashpix.image")
    public static let jfxFax = UniformTypeIdentifier(rawValue: "com.j2.jfx-fax")
    public static let efxFax = UniformTypeIdentifier(rawValue: "com.js.efx-fax")
    public static let sd2Audio = UniformTypeIdentifier(rawValue: "com.digidesign.sd2-audio")
    public static let realMedia = UniformTypeIdentifier(rawValue: "com.real.realmedia")
    public static let realMediaAudio = UniformTypeIdentifier(rawValue: "com.real.realaudio")
    public static let stuffitArchive = UniformTypeIdentifier(rawValue: "com.allume.stuffit-archive")
}

extension UniformTypeIdentifier {
    public static let apng = UniformTypeIdentifier(mimeType: "image/apng")!
    public static let avif = UniformTypeIdentifier(mimeType: "image/avif")!
    public static let webp = UniformTypeIdentifier(rawValue: "org.webmproject.webp")
    public static let flash = UniformTypeIdentifier(mimeType: "video/x-flv")!
    public static let webmVideo = UniformTypeIdentifier(mimeType: "video/webm")!
    public static let _3gp = UniformTypeIdentifier(mimeType: "video/3gpp")!
    public static let oggVideo = UniformTypeIdentifier(mimeType: "video/ogg")!
    public static let webmAudio = UniformTypeIdentifier(mimeType: "audio/webm")!
    public static let oggAudio = UniformTypeIdentifier(mimeType: "audio/ogg")!
    public static let oggApplication = UniformTypeIdentifier(mimeType: "application/ogg")!
}

extension UniformTypeIdentifier {
    public static let wordDocumentXML = UniformTypeIdentifier(rawValue: "org.openxmlformats.wordprocessingml.document")
    public static let excelSpreadsheetXML = UniformTypeIdentifier(rawValue: "org.openxmlformats.spreadsheetml.sheet")
    public static let powerpointPresentationXML = UniformTypeIdentifier(rawValue: "org.openxmlformats.presentationml.presentation")
}

extension UniformTypeIdentifier {
    static let fileExtension = UniformTypeIdentifier(rawValue: kUTTagClassFilenameExtension as String)
    static let mimeType = UniformTypeIdentifier(rawValue: kUTTagClassMIMEType as String)
}
